### ISSUE TITLE
How do I use this to test my filesystem?

### ISSUE THREAD

**Issue by chmduquesne** [rfjakob/fuse-xfstests#1]
I don't understand how to test my filesystem with this test suite.

I started playing and extracted a version of loopbackfs that is simply mounted using

```
ploufs <orig> <mountpoint>
```

The test suite is not exactly working like I expected. I modified ./check-gocryptfs to mount a directory in $TEST_DEV, and it complains immediately that TEST_DEV (/tmp/check-ploufs/testdev) is not a block device or a network filesystem.

Does my filesystem need to come with specific mount options? What are the respective purposes of the directories TEST_DEV, TEST_DIR, SCRATCH_DEV, SCRATCH_MNT?

Thank you!

**Comment by rfjakob** [comment]
I'd recommend to replace the mount command at
https://github.com/rfjakob/fuse-xfstests/blob/gocryptfs/common/rc#L326
and then just run ./check-gocryptfs as-is

**Comment by rfjakob** [comment]
Sorry, this is not yet very friendly for other filesystems! But I think this should work.

**Comment by chmduquesne** [comment]
I would love to see travis running on loopbackfs from go-fuse. I made a pull request on [gocryptfs](https://github.com/rfjakob/gocryptfs/pull/40) to prove that this project could be at least built on travis, and that travis can also run fuse.

**Comment by chmduquesne** [comment]
I enhanced my PR, fuse-xfstests is somehow running on travis. I would love to learn how to use it with e.g. loopbackfs from go-fuse! hopefully I can adapt my own code afterwards :)

**Comment by rfjakob** [comment]
Travis CI is no longer free to use, but for future reference, it did run xfstests against go-fuse loopback and gocryptfs:

https://github.com/rfjakob/fuse-xfstests/blob/d5a48d1d1b38bcce330fa3ff035bdd82ff34ff0e/.travis.yml
